name: Deploy Big Data Infrastructure to AWS

on:
  push:
    branches:
      - developer
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      TF_VAR_FILE: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment file based on branch
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "Ambiente de Produção detectado."
            echo "TF_VAR_FILE=environments/prod/terraform.tfvars" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "developer" ]; then
            echo "Ambiente de Desenvolvimento detectado."
            echo "TF_VAR_FILE=environments/dev/terraform.tfvars" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }} # Ex: arn:aws:iam::123456789012:role/github-actions-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init
        
      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: terraform plan -var-file=${{ env.TF_VAR_FILE }} -no-color

      - name: Terraform Apply
        id: apply
        working-directory: ./terraform
        run: terraform apply -var-file=${{ env.TF_VAR_FILE }} -auto-approve

      - name: Get Terraform Outputs
        id: tf-outputs
        working-directory: ./terraform
        run: |
          echo "scripts_bucket_id=$(terraform output -raw scripts_bucket_id)" >> $GITHUB_OUTPUT
          echo "dags_bucket_id=$(terraform output -raw dags_bucket_id)" >> $GITHUB_OUTPUT

      - name: Sync Glue Scripts to S3
        run: |
          echo "Sincronizando scripts do Glue para s3://${{ steps.tf-outputs.outputs.scripts_bucket_id }}/src/glue/jobs/"
          aws s3 sync ./src/glue/jobs/ s3://${{ steps.tf-outputs.outputs.scripts_bucket_id }}/src/glue/jobs/ --delete

      - name: Sync DAGs to S3
        run: |
          echo "Sincronizando DAGs do Airflow para s3://${{ steps.tf-outputs.outputs.dags_bucket_id }}/src/dags/"
          aws s3 sync ./src/dags/ s3://${{ steps.tf-outputs.outputs.dags_bucket_id }}/src/dags/ --delete
