name: Deploy Big Data Infrastructure to AWS

on:
  push:
    branches:
      - developer
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      TF_VAR_FILE: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables for Terraform
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "Ambiente de Produção detectado."
            echo "TF_VAR_FILE=environments/prod/terraform.tfvars" >> $GITHUB_ENV
            echo "S3_BUCKET_SCRIPTS=bigdata-scripts-prod" >> $GITHUB_ENV
            echo "S3_BUCKET_DAGS=bigdata-dags-prod" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "developer" ]; then
            echo "Ambiente de Desenvolvimento detectado."
            echo "TF_VAR_FILE=environments/dev/terraform.tfvars" >> $GITHUB_ENV
            echo "S3_BUCKET_SCRIPTS=bigdata-scripts-dev" >> $GITHUB_ENV
            echo "S3_BUCKET_DAGS=bigdata-dags-dev" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::SEU_AWS_ACCOUNT_ID:role/github-actions-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform -chdir=terraform init
        
      - name: Terraform Plan
        id: plan
        run: terraform -chdir=terraform plan -var-file=${{ env.TF_VAR_FILE }} -no-color

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=terraform apply -var-file=${{ env.TF_VAR_FILE }} -auto-approve

      - name: Sync Glue Scripts to S3
        run: |
          echo "Sincronizando scripts do Glue para s3://${{ env.S3_BUCKET_SCRIPTS }}/src/glue/jobs/"
          aws s3 sync ./src/glue/jobs/ s3://${{ env.S3_BUCKET_SCRIPTS }}/src/glue/jobs/ --delete

      - name: Sync DAGs to S3
        run: |
          echo "Sincronizando DAGs do Airflow para s3://${{ env.S3_BUCKET_DAGS }}/src/dags/"
          aws s3 sync ./src/dags/ s3://${{ env.S3_BUCKET_DAGS }}/src/dags/ --delete
